### GET CRIMES PREDICT
GET http://localhost:3000/api/crimes/predict/5/4/10/42

### GET CRIMES BY
GET http://localhost:3000/api/crimes/by/20/5/4/10/42

### GET GRID
GET http://localhost:3000/api/grid

### GET CRIMES SAMPLE
GET http://localhost:3000/api/crimes/sample

