version: '2.1'
services:
  back:
    build: back-end/.
    image: crime-back-end
    container_name: crime-back-end
    ports:
      - 3000:3000
    volumes:
      - ./back-end/src:/back-end/src
    command: ['python3', 'src/main.py']
