version: '2.1'
services:
  back:
    build: back-end/.
    image: crime-back-end
    container_name: crime-back-end
    # ports:
    #   - 3001:3000
    expose:
      - 3000
    volumes:
      - ./csv-files:/back-end/csv-files
      - ./back-end/src:/back-end/src
    depends_on:
      db:
        condition: service_healthy
    command: ['python3', 'src/main.py']
  front:
    build: front-end/.
    image: crime-front-end
    container_name: crime-front-end
    # ports:
    #   - 3000:3000
    expose:
      - 3000
    volumes:
      - ./front-end/src:/front-end/src
    depends_on:
      db:
        condition: service_healthy
    command: ['npm', 'start']
  db:
    image: mdillon/postgis
    container_name: crime-db
    # ports:
    #   - 5434:5432
    expose: 
      - 5432
    volumes:
      - ./shape-files:/shape-files
      - ./sh-files:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: crimes
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
  nginx:
    image: nginx:alpine
    container_name: crime-nginx
    tty: true
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - front
      - back
      - db
