version: '2.1'
services:
  back:
    build: back-end/.
    image: crime-back-end
    container_name: crime-back-end
    ports:
      - 3000:3000
    volumes:
      - ./back-end/src:/back-end/src
    command: ['python3', 'src/main.py']
  db:
    image: mdillon/postgis
    container_name: crime-db
    hostname: crime-db-hostname
    ports:
      - '5434:5432'
    volumes:
      - ./shape-files:/shape-files
      - ./sh-files:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: postgres
      POSTGRES_DB: crimes
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
