FROM ubuntu:16.04

ENV FLASK_APP main.py;
ENV FLASK_ENV development
ENV FLASK_PORT 3000

COPY . /back-end
WORKDIR /back-end

RUN apt-get update
RUN apt-get install -y software-properties-common
RUN add-apt-repository ppa:jonathonf/python-3.6

RUN apt-get update
RUN apt-get install -y build-essential python3.6 python3.6-dev python3-pip python3.6-venv

RUN pip3 install --upgrade pip
RUN pip3 install -r requirements.txt

CMD ["/bin/bash"]